version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./root/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./root/etc/nginx/certs:/etc/nginx/certs
      - ./root/etc/apache2:/etc/apache2

  mariadb:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./root/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SomeStrongPass
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "80"
    environment:
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URI=http://127.0.0.1/phpmyadmin/
    depends_on:
      - mariadb

  firefly:
    image: fireflyiii/core:latest
    restart: unless-stopped
    ports:
      - "8080"
    volumes:
      - ./root/var/www/html/storage/upload:/var/www/html/storage/upload
    environment:
      - DEFAULT_LANGUAGE=it_IT
      - DEFAULT_LOCALE=equal
      - TZ=Europe/Rome
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=secret_firefly_password
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp-server
      - MAIL_PORT=25
      - MAIL_FROM=info@fireflyiii.local
      - APP_KEY=SomeRandomStringOf32CharsExactly
      - TRUSTED_PROXIES=**
    depends_on:
      - nginx
      - mariadb

  smtp-server:
    image: bytemark/smtp
    restart: unless-stopped
    ports:
      - "25"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600